ALTER TABLE daily_rates ADD COLUMN rate_id INT PRIMARY KEY AUTO_INCREMENT;

ALTER TABLE daily_income ADD COLUMN income_id INT PRIMARY KEY AUTO_INCREMENT ;

ALTER TABLE daily_income ADD COLUMN created_at TIMESTAMP ;

ALTER TABLE slots ADD COLUMN slot_id INT PRIMARY KEY AUTO_INCREMENT , ADD COLUMN quantity INT NOT NULL;
